name: Cherry-pick pushed branch into main

on:
  push:
    branches-ignore:
      - main

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        run: |
          echo "GITHUB_REF=$GITHUB_REF"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get Branch Name
        id: branch
        run: echo "name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Fetch main
        run: git fetch origin main

      - name: Checkout main
        run: git checkout main

      - name: Cherry-pick
        run: |
          git cherry-pick origin/${{ steps.branch.outputs.name }}..${{ steps.branch.outputs.name }} || echo "Cherry-pick failed"
          git push origin main || echo "Push to main failed"
