name: Cherry-pick to main on any branch push

on:
  push:
    branches: ["**"]

jobs:
  cherry-pick:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Git user
        run: |
          git config user.name "y4zdev"
          git config user.email "dev@y4z.dev"

      - name: Get pushed branch name
        id: vars
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Fetch main branch
        run: git fetch origin main

      - name: Checkout main branch
        run: git checkout main

      - name: Get latest commit hash from pushed branch
        id: commit_hash
        run: |
          echo "COMMIT_HASH=$(git rev-parse origin/${BRANCH_NAME})" >> $GITHUB_ENV

      - name: Cherry-pick commit to main with theirs strategy
        run: |
          git cherry-pick --strategy=recursive -X theirs $COMMIT_HASH

      - name: Push changes to main
        run: git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} main
